services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    ports:
    - 55000:5432
